chipsalliance/caliptra-rtl

- README.md
Add Register docs links to README.md
Also fix a couple formatting nits
> Add Register docs links to README.md

- src/integration/config/caliptra_top_tb.vf
- src/prim/config/compile.yml
- src/prim/config/prim.vf
- src/prim_generic/config/compile.yml
- src/prim_generic/config/prim_generic.vf
- src/spi_host/config/compile.yml
- Updated compile.yml in prim/prim_generic/spi_host
> Update compile.yml +.vf with new files added in spi_host

- .github/scripts/build_tests_matrix.py
- .github/workflows/build-test-verilator.yml
- tools/scripts/Makefile
This PR adds dynamic generation of the CI test matrix based on contents of `src/integration/stimulus/L0_regression.yml`. This removes the need of keeping duplicated list of tests in the CI workflow file. Also with this PR all the regression tests are run in parallel in separate jobs which should speed up the CI execution
> Dynamic generation of the CI test matrix

- src/ahb_lite_bus/rtl/ahb_lite_bus.sv
- src/ahb_lite_bus/rtl/ahb_lite_bus_inf.sv
- src/integration/rtl/caliptra_top.sv
Fixes https://github.com/chipsalliance/caliptra-rtl/issues/104
> Fix for multi-driver hreadyout connection.

- src/aes/rtl/aes_cipher_control.sv
- src/aes/rtl/aes_cipher_control_fsm.sv
- src/aes/rtl/aes_cipher_control_fsm_n.sv
- src/aes/rtl/aes_cipher_control_fsm_p.sv
- src/aes/rtl/aes_cipher_core.sv
- src/aes/rtl/aes_key_expand.sv
- src/aes/rtl/aes_mix_columns.sv
- src/aes/rtl/aes_mix_single_column.sv
- src/aes/rtl/aes_prng_masking.sv
- src/aes/rtl/aes_sbox.sv
- src/aes/rtl/aes_sbox_canright.sv
- src/aes/rtl/aes_sbox_canright_masked.sv
- src/aes/rtl/aes_sbox_canright_masked_noreuse.sv
- src/aes/rtl/aes_sbox_dom.sv
- src/aes/rtl/aes_sbox_lut.sv
- src/aes/rtl/aes_sel_buf_chk.sv
- src/aes/rtl/aes_shift_rows.sv
- src/aes/rtl/aes_sub_bytes.sv
- src/caliptra_prim/rtl/caliptra_prim_lc_sync.sv
- src/csrng/rtl/csrng.sv
- src/csrng/rtl/csrng_core.sv
- src/entropy_src/rtl/entropy_src_core.sv
- src/integration/rtl/caliptra_top.sv
- src/kmac/rtl/keccak_2share.sv
- src/kmac/rtl/keccak_round.sv
- src/kmac/rtl/sha3.sv
- src/kmac/rtl/sha3pad.sv
https://github.com/chipsalliance/caliptra-rtl/issues/182
> Merge dev-goog -> dev-integrate

- src/doe/rtl/doe_reg.rdl
- src/ecc/rtl/ecc_reg.rdl
- src/hmac/rtl/hmac_reg.rdl
- src/libs/rtl/interrupt_regs.rdl
- src/libs/uvmf/qvip_ahb_lite_slave_dir/config_policies/ahb_lite_slave_0_config_policy.svh
- src/sha256/rtl/sha256_reg.rdl
- src/sha512/rtl/sha512_reg.rdl
- src/soc_ifc/rtl/sha512_acc_csr.rdl
- src/soc_ifc/rtl/soc_ifc_internal_reg.rdl
- src/soc_ifc/tb/soc_reg_intrblk_test.svh
This Pull Request is of value for the 1.0 release due to improved clarity in the documentation of interrupt trigger registers.
> Dev msft 20231102

- docs/CaliptraIntegrationSpecification.md
Fixes https://github.com/chipsalliance/Caliptra/issues/152
> Clarify eTRNG usage

- Release_Notes.md
- docs/CaliptraIntegrationSpecification.md
Partially address #263 (still need to update the IP spec to close that issue).
> Specification references to 1.0-rc1 version

- Release_Notes.md
- docs/CaliptraHardwareSpecification.md
- docs/CaliptraIntegrationSpecification.md
> Update doc versions and release notes for 1.0-rc2 version

- src/integration/test_suites/caliptra_top/caliptra_top.c
- src/integration/uvmf_caliptra_top/uvmf_template_output/project_benches/caliptra_top/tb/sequences/src/caliptra_top_rand_sequence.svh
This test emulates the behavior of production systems that issue a mailbox command early in the boot flow (immediately after writing Caliptra fuses) rather than waiting for ready_for_fw to assert.
Integrators may want to use this functionality for the stash measurement command, which provides very small payloads to Caliptra during early boot.
> UVM: Add support for (randomly) running an early mailbox command

- src/ecc/coverage/ecc_top_cov_if.sv
Update signal names in ecc cov
> Update signal names in ecc cov

- src/ecc/rtl/ecc_reg.rdl
- src/hmac/rtl/hmac_reg.rdl
- src/sha256/rtl/sha256_reg.rdl
- src/sha512/rtl/sha512_reg.rdl
> revised rdl comments

- README.md
> Update CDC version in README.md

- docs/CaliptraIntegrationSpecification.md
Update CDC constraints for integration spec.
Added "stable" constraint for rd_data on dmi interface.
> Update CDC Constraint in CaliptraIntegrationSpecification.md

- docs/CaliptraIntegrationSpecification.md
Updated Synthesis results - timing and area
> Update Synthesis Results CaliptraIntegrationSpecification.md

- docs/CaliptraIntegrationSpecification.md
Fix #545.
Signed-off-by: Steven Bellock <sbellock@nvidia.com>
> Fix up JTAG reset in integration specification

- Release_Notes.md
Add line breaks so that markdown renders correctly when viewing on GitHub.
> [DOCS] Update formatting in Release Notes for 1.1

- docs/CaliptraIntegrationSpecification.md
> [DOC] Clarify when fuses may be written in integ spec

- src/integration/rtl/caliptra_top.sv
- src/soc_ifc/rtl/soc_ifc_top.sv
- tools/scripts/reg_doc_gen.py
- Fix scan mode comment in RTL
- Fix lint issue https://github.com/chipsalliance/caliptra-rtl/issues/710
- Add swwe and signals to RDL documentation
> Ckuchta fix scan mode comment

- src/integration/uvmf_caliptra_top/uvmf_template_output/project_benches/caliptra_top/tb/testbench/hdl_top.sv
Apply a reset assertion timing hack that delays reset of the Avery AXI interface by 1ps from the system reset. This resolves an internal race condition that results in Null Object Access on reset assertion, if an AXI transaction is pending.
> [UVM] Apply reset fix for Avery VIP agent

- docs/CaliptraIntegrationSpecification.md
Addresses https://github.com/chipsalliance/Caliptra/issues/320
> [DOC] Clarify and revise the example error handling section related to SRAM implementation

- README.md
Added path here for convenience so people don't have to search the repository for the script.
> [DOC] L0 regression script path added to README

- .gitignore
- src/abr/coverage/clp_abr_top_cov_if.sv
- src/integration/tb/caliptra_top_tb.sv
- src/integration/test_suites/kv_entry_read_err/caliptra_isr.h
- src/integration/test_suites/randomized_mldsa_invalid_verify/caliptra_isr.h
- src/integration/test_suites/randomized_pcr_mldsa_signing/caliptra_isr.h
- src/integration/test_suites/smoke_test_ecc_flow1_kv_ocp_progress/caliptra_isr.h
- src/integration/test_suites/smoke_test_ecc_flow1_kv_ocp_progress/smoke_test_ecc_flow1_kv_ocp_progress.c
- src/integration/test_suites/smoke_test_ecc_flow2_kv_ocp_progress/caliptra_isr.h
- src/integration/test_suites/smoke_test_ecc_flow2_kv_ocp_progress/smoke_test_ecc_flow2_kv_ocp_progress.c
- src/integration/test_suites/smoke_test_kv_mldsa/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_edge/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_errortrigger/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_externalmu/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_kat/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_keygen_sign_vfy_rand/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_keygen_standalone_sign_vfy_rand/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_kv_ocp_progress/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_locked_api/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_sign_rnd/caliptra_isr.h
- src/integration/test_suites/smoke_test_mldsa_zeroize/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem_all_zero_seed/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem_kv/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem_kv_ocp_progress/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem_locked_api/caliptra_isr.h
- src/integration/test_suites/smoke_test_mlkem_shared_key/caliptra_isr.h
Fix for ecc flow1/2 ocp lock tests - error handler and check for kv read/write status
Removed TODOs and FIXMEs from some isr and testbench files
ignoring jtag/tcp files in git
> [TB] Clean fixme/todos, uniquify cov group, fix ecc ocp lock tests

- src/doe/coverage/doe_cov_if.sv
Add missing doe defines to the doe_cov_if file
> [COV] add missing defines to doe cov if
