- .github/workflows/build-test-verilator.yml
The QSPI flash model used requires the --timing flag
> Update Verilator to 5.002

- src/riscv_core/veer_el2/rtl/dec/el2_dec_tlu_ctl.sv
- src/riscv_core/veer_el2/rtl/el2_dma_ctrl.sv
- src/riscv_core/veer_el2/rtl/el2_pic_ctrl.sv
- src/riscv_core/veer_el2/rtl/ifu/el2_ifu.sv
- src/riscv_core/veer_el2/rtl/include/el2_def.sv
- src/riscv_core/veer_el2/rtl/lib/el2_lib.sv
Also adding import statements to various sub-modules
Ran into a few elaboration errors with our internal tooling as documented in https://github.com/chipsalliance/caliptra-rtl/issues/33
> Adding el2_param_t to el2_pkg in riscv_core

- .github/workflows/build-test-verilator.yml
Adding check for "TESTCASE PASSED" string at the end of the CI test per request in https://github.com/chipsalliance/caliptra-rtl/issues/71#issuecomment-1533856632
Also moved the environment variables up in the workflow, which allows it to be shared across the different jobs.
> Adding check for "TESTCASE PASSED" string at the end of CI test

- src/integration/rtl/caliptra_top.sv
- src/riscv_core/veer_el2/rtl/el2_veer.sv
- src/riscv_core/veer_el2/rtl/el2_veer_wrapper.sv
- src/riscv_core/veer_el2/rtl/lib/beh_lib.sv
- src/riscv_core/veer_el2/tb/dasm.svi
This PR updates VeeR-EL2 codebase by bringing in the following changes:
- External scan-chain reset control (https://github.com/chipsalliance/Cores-VeeR-EL2/issues/52, https://github.com/chipsalliance/Cores-VeeR-EL2/pull/61)
- Possibility for injecting custom modules for clock gates (https://github.com/chipsalliance/Cores-VeeR-EL2/issues/50, https://github.com/chipsalliance/Cores-VeeR-EL2/pull/54)
- Correction of default WIDTH parameter for `rvdffppe` (https://github.com/chipsalliance/Cores-VeeR-EL2/issues/73, https://github.com/chipsalliance/Cores-VeeR-EL2/pull/76)
- Fix for swapped mnemonics (https://github.com/chipsalliance/Cores-VeeR-EL2/issues/42, https://github.com/chipsalliance/Cores-VeeR-EL2/pull/77)
> Update VeeR-EL2 codebase

- .github/workflows/build-test-verilator.yml
- README.md
- src/integration/tb/caliptra_top_tb_pkg.sv
- src/integration/tb/caliptra_top_tb_services.sv
- src/integration/tb/dasm.svi
- tools/scripts/Makefile
- Updating to verilator 5.010
- Explicitly defines tasks/functions as static.  (Note: Only the functions/tasks that verilator complained about were modified)  The dasm.svi ones are pulled from upstream: https://github.com/chipsalliance/Cores-VeeR-EL2/blob/b7602fdcf79e19a8e75464df866560fe27c9d439/testbench/dasm.svi#L4
> Updating verilator to 5.010

- src/integration/rtl/caliptra_top.sv
- src/riscv_core/veer_el2/rtl/el2_veer.sv
- src/riscv_core/veer_el2/rtl/el2_veer_wrapper.sv
As a followup to the e-mail discussion this PR reverts the change that introduced the `scan_rst_l` signal.
> Reverted addition of scan_rst_l

- .github/scripts/build_tests_matrix.py
- .github/workflows/build-test-verilator.yml
This PR adds a mechanism for excluding specific CI tests. The list needs to be passed via the `EXCLUDE_TESTS` env variable to the job that builds CI test matrix. Solves https://github.com/chipsalliance/caliptra-rtl/issues/126
Currently the PR has no effect on the CI as the excluded tests are not yet integrated
> Exclude some CI tests for Verilator

- src/integration/tb/caliptra_top_tb.sv
The fix was made in MSFT internal repository, but did not merge correctly into this GitHub repository during a recent sync (git cherry-pick did not recognize the change had been made).
This fix removes the security state driver in caliptra_top_tb so that the driver in caliptra_top_tb_services is the only one.
> Fix for security state multi-driver

- src/aes/rtl/aes_cipher_control.sv
- src/aes/rtl/aes_cipher_control_fsm.sv
- src/aes/rtl/aes_cipher_control_fsm_n.sv
- src/aes/rtl/aes_cipher_control_fsm_p.sv
- src/aes/rtl/aes_cipher_core.sv
- src/aes/rtl/aes_key_expand.sv
- src/aes/rtl/aes_mix_columns.sv
- src/aes/rtl/aes_mix_single_column.sv
- src/aes/rtl/aes_prng_masking.sv
- src/aes/rtl/aes_sbox.sv
- src/aes/rtl/aes_sbox_canright.sv
- src/aes/rtl/aes_sbox_canright_masked.sv
- src/aes/rtl/aes_sbox_canright_masked_noreuse.sv
- src/aes/rtl/aes_sbox_dom.sv
- src/aes/rtl/aes_sbox_lut.sv
- src/aes/rtl/aes_sel_buf_chk.sv
- src/aes/rtl/aes_shift_rows.sv
- src/aes/rtl/aes_sub_bytes.sv
- src/caliptra_prim/rtl/caliptra_prim_lc_sync.sv
- src/csrng/rtl/csrng.sv
- src/csrng/rtl/csrng_core.sv
- src/entropy_src/rtl/entropy_src_core.sv
- src/integration/rtl/caliptra_top.sv
- src/kmac/rtl/keccak_2share.sv
- src/kmac/rtl/keccak_round.sv
- src/kmac/rtl/sha3.sv
- src/kmac/rtl/sha3pad.sv
Updates taken directly from https://github.com/chipsalliance/caliptra-rtl/issues/182#issuecomment-1714410764
> Update Package Imports

- .github/workflows/interactive-debugging.yml
- src/integration/test_suites/infinite_loop/common.tcl
- src/integration/test_suites/infinite_loop/infinite_loop.s
- src/integration/test_suites/infinite_loop/jtag_cg.tcl
- src/integration/test_suites/infinite_loop/peripheral_access.tcl
- src/integration/test_suites/infinite_loop/regdump_golden.txt
Related to #162.
This PR adds a test for JTAG accesses while clock gating is enabled and the core is halted.
> Add test for Mailbox JTAG accesses with clock gating

- docs/Caliptra_rtl.md
This is an initial markdown conversion of the HW integration guide, generated from .docx snapshot on Oct 18. Includes fixes / updates for:
- accepted all SME revisions
- table updates: converted to markdown with no html, refactored several to remove table nesting, renumbered and labeled all tables
- removed heading numbers
- general manual formatting updates
Images are not included in this PR; these are todo in future PR.
> initial markdown conversion

- src/soc_ifc/rtl/soc_ifc_external_reg.rdl
> RDL: Add RNG unavail bit to dbg manuf reg description

- src/integration/rtl/caliptra_top.sv
- src/riscv_core/veer_el2/rtl/dmi/dmi_wrapper.v
- src/riscv_core/veer_el2/rtl/dmi/rvjtag_tap.v
- src/riscv_core/veer_el2/rtl/el2_veer_wrapper.sv
- src/riscv_core/veer_el2/tb/el2_veer_wrapper_tb.sv
- tools/scripts/openocd/target/veer-el2-rst.cfg
- tools/scripts/openocd/target/veer-el2.cfg
This PR removes support for read IDCODE instruction from the TAP. This addresses https://github.com/chipsalliance/caliptra-rtl/issues/289 where Caliptra is to be connected to a system JTAG as a submodule.
> Remove read IDCODE instruction from VeeR JTAG TAP

- README.md
- tools/scripts/Makefile
Add instructions to copy test vector generators
Add explanation of optional plusargs for using test vector generators
Potentially addresses the issue behind #307
> [README] Update VCS steps

- tools/scripts/Makefile
This PR fixes VCS build by adding missing C sources necessary for JTAG simulation with DPI. Fixes https://github.com/chipsalliance/caliptra-rtl/issues/297
> Fix VCS DPI build

- docs/CaliptraIntegrationSpecification.md
Follow-up to #279.
Signed-off-by: Steven Bellock <sbellock@nvidia.com>
> Extend new APB defines in integration document

- docs/CaliptraHardwareSpecification.md
- docs/CaliptraIntegrationSpecification.md
Removes references to outdated HW diagram, adds links to current diagram in main spec, and removes phrase that refers to supporting BMI profile. Aligns with [PR 154](https://github.com/chipsalliance/Caliptra/pull/154) in main spec
> remove profile for 1.0

- docs/CaliptraIntegrationSpecification.md
> Specify TRNG timing requirement

- docs/CaliptraIntegrationSpecification.md
> Expand details on iTRNG block and PTRNG source

- .github/scripts/gdb_test.sh
- .github/workflows/build-test-verilator.yml
- .github/workflows/interactive-debugging.yml
- README.md
- src/integration/test_suites/fw_test_rom/fw_test_rom.makefile
- src/integration/test_suites/infinite_loop/dump_and_compare.sh
- src/integration/test_suites/infinite_loop/mem_access.sh
- src/integration/test_suites/infinite_loop/peripheral_access.sh
- tools/scripts/Makefile
This PR introduces few changes:
- switches to the active RISC-V toolchain version in CI,
- ensures in `Makefile` that RISC-V toolchain is installed, it checks for bot 64-bit and 32-bit versions, in that order,
- uses new `march` syntax for `Zifencei` extension in versions higher or equal to 12.2.0 of RISC-V toolchain.
Solves https://github.com/chipsalliance/caliptra-rtl/issues/371.
> Fix usage of RISC-V toolchain

- docs/CaliptraIntegrationSpecification.md
This PR addresses #358 by adding a table to the Integration spec that describes which RTL modifications integrators are expected to make.
Several other issues in the caliptra-rtl repository also discuss concerns over ambiguous synchronizer requirements and implementation:
* #218
* #315
* #333
* #366
This update may become obsolete and require further spec updates once https://github.com/chipsalliance/Cores-VeeR-EL2/pull/56 has been finalized and merged back into the caliptra-rtl repository.
Resolves #333
Resolves #358
> Add RTL file list to be modified by integrators

- .github/workflows/build-test-verilator.yml
- .github/workflows/interactive-debugging.yml
- README.md
- src/integration/test_suites/fw_test_rom/fw_test_rom.makefile
- tools/scripts/Makefile
This PR restores RISC-V toolchain to the version used before #377. The toolchain is hosted in the https://github.com/chipsalliance/caliptra-tools repository
> CI: use risc-v gcc 12.1.0

- README.md
- Release_Notes.md
- docs/CaliptraHardwareSpecification.md
- docs/CaliptraIntegrationSpecification.md
Documentation versioning for final 1.0 release.
> Update documentation version numbers from 1.0-rc2 to 1.0

- src/integration/tb/caliptra_top_tb_services.sv
A recent change to the Caliptra top tb that makes verbose per-cycle logs off by default introduced a single typo that deviates from the intended behavior (a simple unary negation is removed).
> Fix typo on logging plusarg check in top level TB

- src/sha256/rtl/sha256.sv
- src/sha256/tb/sha256_ctrl_tb.sv
- Eliminated one cycle delay for wntz loop execution
- Fixed parameters during computation, such as mode, wntz_w, and wntz_n_mode (parameter changes during the process are disregarded)
- Included a test scenario for triggering wntz mode in the subsequent cycle of regular sha256 initialization command
- Simplified the code
> removed delayed wntz starting and fixed FPV bug

- src/hmac/uvmf_2022/uvmf_template_output/project_benches/HMAC/tb/testbench/hdl_top.sv
- src/integration/test_suites/libs/riscv_hw_if/link.ld
- src/integration/test_suites/smoke_test_ras/smoke_test_ras.ld
- src/sha512/uvmf_sha512/uvmf_template_output/project_benches/SHA512/tb/testbench/hdl_top.sv
Recent addition of assertions to check for X values on register interfaces revealed some issues with HMAC/SHA512 UVM testbenches. Fix those issues by driving undriven signals with 0 - until an improved solution is available.
Fix an issue with validation firmware linker script - it was excluding both sections `sdata` and `data.datavault`, which causes some issues sims (detected this while doing Caliptra SEED work, but applicable to main also).
> UVM: Fix some failing scenarios

- src/sha512_masked/rtl/sha512_masked_defines_pkg.sv
Declare functions in the sha512 masked package as 'automatic' to resolve a synthesis warning
> Lint fix to resolve synthesis issue for SHA512 masked IP

- src/integration/stimulus/L0_regression.yml
- src/integration/stimulus/testsuites/caliptra_top_nightly_directed_regression.yml
Update paths to fw_test files in nightly directed regression and disable those tests as they are obsolete.
Fix a typo in the L0 regression test list that was introduced alongside new tests for 1.1 features (Winternitz accelerator)
> Fix typos from regression test lists

- src/soc_ifc/tb/soc_ifc_tb.sv
Resolves a regression failure due to detecting X values from the SRAM
> [SOC_IFC_TB] Initialize mailbox RAM in unittest

- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sha_accel_sequence.svh
fixing sha accel sequence constraint solver issue due to reduced mailbox size in caliptra seed
Larger test vectors won't fit inside the mailbox, reducing the range of vectors the test can pick from
> Fix for sha accel seq constraint solver

- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_dlen_invalid_sequence.svh
Add code to predict/anticipate an error condition when injecting an invalid DLEN value as an error test sequence. This resolves an error that fires when the (expected) failure status is returned for the command.
> [UVM] Fix regression failure caused by a false negative

- src/integration/test_suites/caliptra_rt/caliptra_rt.c
- src/integration/test_suites/libs/soc_ifc/soc_ifc.c
- src/integration/test_suites/libs/soc_ifc/soc_ifc.h
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sram_double_bit_flip_sequence.svh
Implement a firmware feature (for the validation code used in UVM tests) to sanitize the mailbox after detecting double-bit ECC error, to mirror the workaround required in 1.1 Firmware as per https://github.com/chipsalliance/caliptra-rtl/issues/399.
This is a temporary solution that should be removed for 2.0, as the mailbox should be modified to avoid spurious data prefetches.
> [UVM] Implement mailbox sanitize feature in val fw to suppress regression failure

- docs/CaliptraHardwareSpecification.md
Replace non-inclusive language
> Inclusive language

- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_execute_execute.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_lock_lock.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_unlock_unlock.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/src/soc_ifc_predictor.svh
Resolves an issue where mbox_lock is accessed simultaneously by SoC and by Caliptra FW and UVM predictor fails to accurately track FSM transitions.
> [UVM] Fix for a regression failure caused by cycle-inaccurate FSM prediction logic in TB

- .github/workflow_metadata/README.md
- .github/workflows/doc-gen.yml
- docs/CaliptraReleaseChecklist.md
Currently the docs workflow only publishes documentation for registers at main. To make it easier to look up registers for 1.x, also publish the registers from the patch_v1.1 branch.
This was tested on my fork of this repo. See sample output:
* Workflow run: https://github.com/jhand2/caliptra-rtl/actions/runs/12472498726
* main: https://jhand2.github.io/caliptra-rtl/main/internal-regs/?p=
* 1.1: https://jhand2.github.io/caliptra-rtl/v1_1/internal-regs/?p=
> Publish HTML docs for 1.1 RTL in addition to main

- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_intr_block_rf_ext_error_internal_intr_r_base.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_intr_block_rf_ext_notif_internal_intr_r_base.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_delay_job_intr_block_rf_ext.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_model_top_pkg.sv
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/interface_packages/soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_configuration.svh
- src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/interface_packages/soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_monitor_bfm.sv
Update callbacks to enforce hwset precedence over swclr on interrupt status regs.
> [UVM] Fix a race condition between interrupt callbacks

- docs/CaliptraIntegrationSpecification.md
- src/axi/rtl/axi_dma_reg.rdl
- src/axi/rtl/axi_sub_arb.sv
- src/entropy_src/config/compile.yml
- src/entropy_src/config/entropy_src_tb.vf
- src/integration/rtl/caliptra_top.sv
- src/integration/tb/caliptra_top_tb.sv
- src/integration/uvmf_caliptra_top/uvmf_template_output/project_benches/caliptra_top/tb/testbench/hdl_top.sv
- src/soc_ifc/rtl/soc_ifc_reg.sv
- src/soc_ifc/rtl/soc_ifc_subsystem_reg.rdl
- src/soc_ifc/stimulus/testsuites/uvmf_soc_ifc_promote_regression.yml
AXI Sub Arb fix. 
* Resolves #753 
Add synchronizers to input signals from subsystem recovery interface. 
Export RISC-V trace signals for debug.
Move SS dbg unlock level reg to pwrgood so it's sticky and persists across warm resets without having to redo the debug unlock flow.
> [RTL] AXI Sub Arb fix. Add recovery inf synchros. Export trace signals. Move SS dbg unlock reg to pwrgood.

- src/sha512/rtl/sha512.sv
Fixing sticky lock bits in gen hash operation
Zeroize will clear the lock bits after gen hash operation.
> gen hash sticky lock bits bugfix

- docs/CaliptraIntegrationSpecification.md
Internally, Caliptra firmware uses 0xFFFFFFFFF to denote measurements performed by Caliptra itself. For this reason, this value can not be used for any SoC AXI user. Firmware will fail any mailbox requests from this user.
> Mark AXI user 0xFFFF_FFFF as reserved
